Repository IATI/iatipublisher, pull requests merged in 2023-03, with the labels that each got.

#1118 Add CSP Header
  docker/nginx.conf.template
Labels: type: enhancement

#1119 comment out csp header
  docker/nginx.conf.template
Labels: priority: critical

#1135 update env
  packages/development/sealed-secret.yaml
  packages/staging/sealed-secret.yaml
Labels: priority: critical, DevOps

#1144 update sealed secret for staging and prod
  packages/production/sealed-secret.yaml
  packages/staging/sealed-secret.yaml
Labels: priority: critical

#1143 Reviewed: 1131-update-env-credential
  packages/development/sealed-secret.yaml
Labels: WTD

#1145 Review: 1012 develop script fixes
  app/Console/Commands/MigrateOrganizationCommand.php
  app/IATI/Models/Activity/Activity.php
  app/IATI/Models/Activity/ActivityPublished.php
  app/IATI/Models/Activity/ActivitySnapshot.php
  app/IATI/Models/Activity/BulkPublishingStatus.php
  app/IATI/Models/Activity/Indicator.php
  app/IATI/Models/Activity/Period.php
  app/IATI/Models/Activity/Result.php
  app/IATI/Models/Activity/Transaction.php
  app/IATI/Models/Document/Document.php
  app/IATI/Models/ImportActivityError/ImportActivityError.php
  app/IATI/Models/Organization/Organization.php
  app/IATI/Models/Organization/OrganizationPublished.php
  app/IATI/Models/Setting/Setting.php
  app/IATI/Models/User/User.php
  app/IATI/Repositories/Activity/ResultRepository.php
  app/IATI/Services/Activity/ResultService.php
  app/IATI/Traits/MigrateActivityPublishedTrait.php
  app/IATI/Traits/MigrateActivityResultsTrait.php
  app/IATI/Traits/MigrateActivityTrait.php
  app/IATI/Traits/MigrateDocumentFileTrait.php
  app/IATI/Traits/MigrateOrganizationPublishedTrait.php
  app/IATI/Traits/MigrateOrganizationTrait.php
  config/filesystems.php
Labels: WTD
